### ISSUE TITLE
The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by marcaaron** [leveluptuts/React-Testing-For-Beginners#1]
Received the following error when attempting to yarn install

```
error eslint@5.3.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
```
Using node v9.3.0

Deleted yarn.lock and ran `npm install` without errors.

**Comment by stolinski** [comment]
You need to upgrade your node version to be one of the supported aka over 9.10 or 8.11. The latest LTS 8.11 works or the current 10.9.0 should work.

**Comment by marcaaron** [comment]
sorry had a senior moment and was like wait 9.3 is definitely more than 9.1 🧠
